apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sostrongind-com-tls
spec:
  secretName: sostrongind-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sostrongind.com
  dnsNames:
    - sostrongind.com
    - www.sostrongind.com
